- validate/schema.yaml
- validate/validate.py
Initial yaml schema validation
> add schema validation (yaml format)

- data/countries/de/nrw/data.yaml
- data/countries/de/nrw/rheinisch-bergischer-kreis/data.yaml
- Adds KV Rhein-Berg
- Fixes OV Rösrath email (#4)
- Creates sub-dir for Rheinisch-Bergischer Kreis, as I intend to add the other OV entries soon
> Add KV Rhein-Berg, fix Rösrath email

- .travis.yml
- README.md
- data/countries/de/bw/data.yaml
Data source: [gruene-bw.de/partei/kreisverbaende](https://www.gruene-bw.de/partei/kreisverbaende/)
I got the data from the html of the link above (and /page/[2](https://www.gruene-bw.de/partei/kreisverbaende/page/2/)-[5](https://www.gruene-bw.de/partei/kreisverbaende/page/5/)) and extracted it with regexing and a python script that uses the xml.etree library.
Currently, some lines in the yaml file seem to be too long.
Please give feedback and review.
> add data for BW

- data/countries/de/by/data.yaml
- still wip (by now only landesverband and bezirksverbände)
- introducing new `INSTAGRAM` url type
- currently only websites for bezirksverbände
> add bavaria (BY) data

- data/countries/de/he/data.yaml
source: gruene-hessen.de/partei/gruene-vor-ort-in-hessen
> Add hessen data

- data/countries/de/th/data.yaml
Add Thüringen data from gruene-thueringen.de/gruene-vor-ort
How to handle Regionalverbände in Thüringen? (@marians) Should we add a new level `DE:REGIONALVERBAND`?
If yes, we should append:
```
---
country: DE
state: Thüringen
type: REGIONAL_CHAPTER
level: DE:REGIONALVERBAND
district: Wartburgkreis/Eisenach
urls:
- type: WEBSITE
url: http://www.gruene-wartburgkreis-eisenach.de/
- type: FACEBOOK
url: https://www.facebook.com/Gruene.WAK.EA/
---
country: DE
state: Thüringen
type: REGIONAL_CHAPTER
level: DE:REGIONALVERBAND
district: Sonneberg- Hildburghausen
urls:
- type: WEBSITE
url: http://gruene-sonneberg-hildburghausen.de/
- type: FACEBOOK
url: https://www.facebook.com/gruenesonneberg/
---
country: DE
state: Thüringen
type: REGIONAL_CHAPTER
level: DE:REGIONALVERBAND
district: …
```
> Add th data

- data/countries/de/ni/data.yaml
source: https://www.gruene-niedersachsen.de/partei/gruene-vor-ort/
including OVs
> Add niedersachsen data

- data/countries/de/bb/data.yaml
source: gruene-brandenburg.de/vorort
> Add bb data

- data/countries/de/hh/data.yaml
source: hamburg.gruene.de/partei/vor-ort
> add hamburg data

- data/countries/de/bb/data.yaml
- data/countries/de/be/data.yaml
- data/countries/de/bw/data.yaml
- data/countries/de/by/data.yaml
- data/countries/de/hb/data.yaml
- data/countries/de/he/data.yaml
- data/countries/de/hh/data.yaml
- data/countries/de/mv/data.yaml
- data/countries/de/ni/data.yaml
- data/countries/de/nw/data.yaml
- data/countries/de/rp/data.yaml
- data/countries/de/sh/data.yaml
- data/countries/de/sl/data.yaml
- data/countries/de/st/data.yaml
- data/countries/de/th/data.yaml
The sociallinks were added by a scraper for GCMS/Urwahl3000 Websites.
Please have a critical look at them, I might have overseen issues!
> Add sociallinks

- data/countries/de/rp/data.yaml
add ortsverbaende in rhein-pfalz-kreis
> add ovs in rhein-pfalz-kreis

- data/countries/de/ni/data.yaml
add the KVs I forgot on the first import. Fixes #49
> fix NI issues

- data/countries/de/bb/data.yaml
- data/countries/de/be/data.yaml
- data/countries/de/bw/data.yaml
- data/countries/de/by/data.yaml
- data/countries/de/data.yaml
- data/countries/de/hb/data.yaml
- data/countries/de/he/data.yaml
- data/countries/de/hh/data.yaml
- data/countries/de/mv/data.yaml
- data/countries/de/ni/data.yaml
- data/countries/de/nw/data.yaml
- data/countries/de/rp/data.yaml
- data/countries/de/sh/data.yaml
- data/countries/de/sl/data.yaml
- data/countries/de/sn/data.yaml
- data/countries/de/st/data.yaml
- data/countries/de/th/data.yaml
I added the wikipedia links to BV and LVs (there are no other "lower-level" wiki links"
> add all wikipedia links

- data/countries/de/bw/data.yaml
- data/countries/de/by/data.yaml
- data/countries/de/he/data.yaml
- data/countries/de/hh/data.yaml
- data/countries/de/mv/data.yaml
- data/countries/de/ni/data.yaml
- data/countries/de/nw/data.yaml
- data/countries/de/rp/data.yaml
- data/countries/de/sh/data.yaml
- data/countries/de/sl/data.yaml
- data/countries/de/sn/data.yaml
- data/countries/de/st/data.yaml
For reference:
I also found the following instagram links which belong to OVs that are not yet added:
```https://www.instagram.com/gruene.fehmarn/
https://www.instagram.com/gruenesalzkotten/
https://www.instagram.com/gruenehalstenbek/
https://www.instagram.com/gruene.marbach/
https://www.instagram.com/gruenewentorf/
```
TODO:
> add a bunch of instagram links

- data/countries/de/nw/data.yaml
> fix Remscheids insta

- data/countries/de/bw/data.yaml
- data/countries/de/bw/rems-murr/data.yaml
- data/countries/de/by/data.yaml
- data/countries/de/mv/data.yaml
- data/countries/de/nw/rhein-kreis-neuss/data.yaml
- data/countries/de/rp/data.yaml
- data/countries/de/sl/data.yaml
fix/delete erroneous facebook links
> Fix facebook

- data/countries/de/bb/oder-spree/data.yaml
> Add DE/BB/Fürstenwalde

- data/countries/de/bb/data.yaml
- data/countries/de/bw/breisgau-hochschwarzwald/data.yaml
- data/countries/de/bw/data.yaml
- data/countries/de/by/data.yaml
- data/countries/de/by/fuerstenfeldbruck/data.yaml
- data/countries/de/he/lahn-dill/data.yaml
- data/countries/de/he/odenwald/data.yaml
- data/countries/de/ni/data.yaml
- data/countries/de/ni/goettingen/data.yaml
- data/countries/de/ni/hannover/data.yaml
- data/countries/de/ni/rotenburg-wuemme/data.yaml
- data/countries/de/nw/data.yaml
- data/countries/de/nw/recklinghausen/data.yaml
- data/countries/de/rp/data.yaml
- data/countries/de/st/data.yaml
Fix or remove offline social media links
> fix or remove social media links

- data/countries/de/bb/data.yaml
- data/countries/de/be/data.yaml
- data/countries/de/data.yaml
- data/countries/de/sh/rendsburg-eckernfoerde/data.yaml
* Add/fix social links
* add persons
* add berlin social links
> Add/fix social links, add persons

- data/countries/de/he/hochtaunus/data.yaml
update some HTK data (Website Grävenwiesbach, Facebook Friedrichsdorf, Twitter KV and Bad Homburg)
> HTK updates

- data/countries/de/by/data.yaml
Added some members of the bavarian parliament (Issues #185, #186, #187)
> Add individuals from Bavaria

- data/countries/de/by/data.yaml
- data/countries/de/by/regensburg-land/data.yaml
Die Untergliederung bezeichnet sich als "Ortsgruppe" und eben nicht als OV. Ich weiß nicht, ob wir hierfür einen eigenen Level einrichten wollen?
> created subdir for Regensburg-Land, added Obertraubling

- data/countries/de/mv/landkreis-rostock/data.yaml
Reference: https://chatbegruenung.de/channel/green-spider?msg=suMWWYjNEahZ97WLL
> Add OV to KV Landkreis Rostock

- data/countries/de/by/aschaffenburg-land/data.yaml
Added WEBSITE and FACEBOOK for OV Mömbris
Requested by @dornbeo0 in #green-spider on chatbegruenung.de
> Added OV Mömbris

- data/countries/de/be/data.yaml
changed many URLs for federal state 'be' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'be'

- data/countries/de/st/data.yaml
- data/countries/de/st/mansfeld-suedharz/data.yaml
changed many URLs for federal state 'st' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'st'

- data/countries/de/hh/data.yaml
changed many URLs for federal state 'hh' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'hh'

- data/countries/de/mv/data.yaml
- data/countries/de/mv/landkreis-rostock/data.yaml
changed many URLs for federal state 'mv' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'mv'

- data/countries/de/rp/alzey-worms/data.yaml
- data/countries/de/rp/bad-duerkheim/data.yaml
- data/countries/de/rp/bad-kreuznach/data.yaml
- data/countries/de/rp/bernkastel-wittlich/data.yaml
- data/countries/de/rp/data.yaml
- data/countries/de/rp/germersheim/data.yaml
- data/countries/de/rp/mainz-bingen/data.yaml
- data/countries/de/rp/mayen-koblenz/data.yaml
- data/countries/de/rp/neuwied/data.yaml
- data/countries/de/rp/rhein-hunsrueck/data.yaml
- data/countries/de/rp/rhein-lahn/data.yaml
- data/countries/de/rp/rhein-pfalz/data.yaml
- data/countries/de/rp/suedliche-weinstrasse/data.yaml
changed many URLs for federal state 'rp' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'rp'

- data/countries/de/by/aichach-friedberg/data.yaml
- data/countries/de/by/ansbach/data.yaml
- data/countries/de/by/augsburg-land/data.yaml
- data/countries/de/by/bad-toelz-wolfrathshausen/data.yaml
- data/countries/de/by/bayreuth-land/data.yaml
- data/countries/de/by/data.yaml
- data/countries/de/by/ebersberg/data.yaml
- data/countries/de/by/erlangen-land/data.yaml
- data/countries/de/by/forchheim/data.yaml
- data/countries/de/by/fuerstenfeldbruck/data.yaml
- data/countries/de/by/fuerth-land/data.yaml
- data/countries/de/by/kelheim/data.yaml
- data/countries/de/by/landsberg-lech/data.yaml
- data/countries/de/by/miesbach/data.yaml
- data/countries/de/by/muenchen-land/data.yaml
- data/countries/de/by/muenchen/data.yaml
- data/countries/de/by/nuernberg-land/data.yaml
- data/countries/de/by/oberallgaeu/data.yaml
- data/countries/de/by/rosenheim/data.yaml
- data/countries/de/by/schweinfurt/data.yaml
- data/countries/de/by/starnberg/data.yaml
- data/countries/de/by/weilheim-schongau/data.yaml
- data/countries/de/by/weissenburg-gunzenhausen/data.yaml
- data/countries/de/by/wuerzburg/data.yaml
changed many URLs for federal state 'by' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'by'

- data/countries/de/bb/data.yaml
- data/countries/de/bb/potsdam-mittelmark/data.yaml
changed many URLs for federal state 'bb' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'bb'

- data/countries/de/th/data.yaml
changed many URLs for federal state 'th' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'th'

- data/countries/de/sh/data.yaml
- data/countries/de/sh/nordfriesland/data.yaml
- data/countries/de/sh/ostholstein/data.yaml
- data/countries/de/sh/pinneberg/data.yaml
- data/countries/de/sh/ploen/data.yaml
- data/countries/de/sh/rendsburg-eckernfoerde/data.yaml
- data/countries/de/sh/schleswig-flensburg/data.yaml
- data/countries/de/sh/segeberg/data.yaml
- data/countries/de/sh/steinburg/data.yaml
- data/countries/de/sh/stormarn/data.yaml
changed many URLs for federal state 'sh' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'sh'

- data/countries/de/sn/data.yaml
changed many URLs for federal state 'sn' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'sn'

- data/countries/de/ni/ammerland/data.yaml
- data/countries/de/ni/aurich-norden/data.yaml
- data/countries/de/ni/celle/data.yaml
- data/countries/de/ni/cuxhaven/data.yaml
- data/countries/de/ni/data.yaml
- data/countries/de/ni/diepholz/data.yaml
- data/countries/de/ni/emsland-nord/data.yaml
- data/countries/de/ni/emsland-sued/data.yaml
- data/countries/de/ni/goettingen/data.yaml
- data/countries/de/ni/grafschaft-bentheim/data.yaml
- data/countries/de/ni/hameln-pyrmont/data.yaml
- data/countries/de/ni/hannover/data.yaml
- data/countries/de/ni/harburg-land/data.yaml
- data/countries/de/ni/heidekreis/data.yaml
- data/countries/de/ni/hildesheim/data.yaml
- data/countries/de/ni/lueneburg/data.yaml
- data/countries/de/ni/nienburg/data.yaml
- data/countries/de/ni/northeim-einbeck/data.yaml
- data/countries/de/ni/oldenburg-land/data.yaml
- data/countries/de/ni/osnabrueck-land/data.yaml
- data/countries/de/ni/osterholz/data.yaml
- data/countries/de/ni/rotenburg-wuemme/data.yaml
- data/countries/de/ni/stade/data.yaml
- data/countries/de/ni/verden/data.yaml
- data/countries/de/ni/wesermarsch/data.yaml
- data/countries/de/ni/wolfenbuettel/data.yaml
changed many URLs for federal state 'ni' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'ni'

- data/countries/de/hb/data.yaml
changed many URLs for federal state 'hb' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'hb'

- data/countries/de/bw/bodenseekreis/data.yaml
- data/countries/de/bw/boeblingen/data.yaml
- data/countries/de/bw/data.yaml
- data/countries/de/bw/esslingen/data.yaml
- data/countries/de/bw/heilbronn/data.yaml
- data/countries/de/bw/karlsruhe-land/data.yaml
- data/countries/de/bw/konstanz/data.yaml
- data/countries/de/bw/ludwigsburg/data.yaml
- data/countries/de/bw/main-tauber/data.yaml
- data/countries/de/bw/neckar-bergstrasse/data.yaml
- data/countries/de/bw/odenwald-kraichgau/data.yaml
- data/countries/de/bw/ortenau/data.yaml
- data/countries/de/bw/rems-murr/data.yaml
- data/countries/de/bw/reutlingen/data.yaml
- data/countries/de/bw/tuebingen/data.yaml
- data/countries/de/bw/wangen/data.yaml
changed many URLs for federal state 'bw' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'bw'

- data/countries/de/sl/data.yaml
changed many URLs for federal state 'sl' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'sl'

- data/countries/de/he/bergstrasse/data.yaml
- data/countries/de/he/darmstadt-dieburg/data.yaml
- data/countries/de/he/data.yaml
- data/countries/de/he/frankfurt/data.yaml
- data/countries/de/he/gross-gerau/data.yaml
- data/countries/de/he/hersfeld-rotenburg/data.yaml
- data/countries/de/he/hochtaunus/data.yaml
- data/countries/de/he/kassel-land/data.yaml
- data/countries/de/he/lahn-dill/data.yaml
- data/countries/de/he/limburg-weilburg/data.yaml
- data/countries/de/he/main-kinzig/data.yaml
- data/countries/de/he/main-taunus/data.yaml
- data/countries/de/he/marburg-biedenkopf/data.yaml
- data/countries/de/he/odenwald/data.yaml
- data/countries/de/he/offenbach-land/data.yaml
- data/countries/de/he/rheingau-taunus/data.yaml
- data/countries/de/he/schwalm-eder/data.yaml
- data/countries/de/he/waldbeck-frankenberg/data.yaml
- data/countries/de/he/wetterau/data.yaml
changed many URLs for federal state 'he' (see netzbegruenung#237)
> Bulk-modified URLs for federal state 'he'

- data/countries/de/sh/data.yaml
- data/countries/de/sh/herzogtum-lauenburg/data.yaml
This time the validator was happy. Seriously.
> Add herzogtum lauenburg

- data/countries/de/nw/kleve/data.yaml
Adding social media URLs, updating websites
> URL update for Kleve
